language: rust

rust:
  - stable

cache: cargo

sudo: false

# Dependencies of kcov, used for cargo-travis
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libbz2-dev
      - binutils-dev
      - libiberty-dev
      - cmake
      - musl
      - musl-dev
      - musl-tools
    sources:
      - kalakris-cmake

before_script:
  - cargo install cargo-travis || true
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup component add rustfmt-preview
  - rustup target add x86_64-unknown-linux-musl

script:
  - cargo fmt --version
  - cargo fmt -- --check
  - cargo build
  - cargo test
  - cargo build --no-default-features
  - cargo test --no-default-features
  - cargo build --target x86_64-unknown-linux-musl
  - cargo test --target x86_64-unknown-linux-musl
  - cargo build --target x86_64-unknown-linux-musl --no-default-features
  - cargo test --target x86_64-unknown-linux-musl --no-default-features

after_success:
  - cargo coveralls


env:
  global:
    - secure: ioWAhmR9VNa96Zn3UvY46bzys5LY6rHezT/nxsX6Wc0tZ3s/pk45wRKl9mU+oX+29EXMl2EXZZzsUlmY9AWNS34uQdBJ5HB68k2l2Cl44f/R4fQiFbkucCaCuTLDDshRsQInHTrsIjiB0tvjCG1tkNWQlgDIB4yeqPcL+YrmeMs=
    - RUST_BACKTRACE=1
