on:
  push:
    branches:
      - master

name: release-please

jobs:
  release-please:
    if: github.repository_owner == 'rust-bio'
    runs-on: ubuntu-latest
    steps:

      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release_sys
        with:
          release-type: rust
          package-name: hts-sys
          monorepo-tags: true
          path: hts-sys

      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release_main
        with:
          release-type: rust
          package-name: rust-htslib
          bump-minor-pre-major: Yes
          monorepo-tags: true

      - uses: actions/checkout@v2
        if: ${{ steps.release_main.outputs.release_created || steps.release_sys.outputs.release_created }}
        with:
          submodules: true

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        if: ${{ steps.release_main.outputs.release_created || steps.release_sys.outputs.release_created }}
        with:
          toolchain: stable
          override: true

      - name: Install system dependencies
        if: ${{ steps.release_main.outputs.release_created || steps.release_sys.outputs.release_created }}
        run: |
            sudo apt-get install --yes zlib1g-dev libbz2-dev musl musl-dev musl-tools clang libc6-dev

      - uses: Swatinem/rust-cache@v1.3.0
        if: ${{ steps.release_main.outputs.release_created || steps.release_sys.outputs.release_created }}
      
      - name: Publish hts-sys
        if: ${{ steps.release_sys.outputs.release_created }}
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path hts-sys/Cargo.toml --token ${{ secrets.CRATES_IO_TOKEN }}
      
      - name: Publish rust-htslib
        if: ${{ steps.release_main.outputs.release_created }}
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CRATES_IO_TOKEN }}

      # - uses: katyo/publish-crates@v1
      #   if: ${{ steps.release_main.outputs.release_created || steps.release_sys.outputs.release_created }}
      #   with:
      #     registry-token: ${{ secrets.CRATES_IO_TOKEN }}
